
name: Refresh CovidVIC Map

on:
  push:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */8 * * *'

jobs:
  build:

    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          pip install -r get_data/requirements.txt
      - name: fetch data
        env: 
          GCP_API_KEY: ${{ secrets.API_KEY }}
        run: python get_data.py -o ../src/data.json
        working-directory: get_data
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY }}
          publish_dir: ./build